name: LEMP Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # âœ… Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version  # verify installation

      # ğŸ— Build the Docker Images
      - name: Build the Docker Images
        run: docker compose build

      # ğŸ”‘ Login to Docker Hub
      - name: Logging into the Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ğŸ“¤ Push the Docker Images
      - name: Push the Docker Images to the Docker Hub
        run: docker compose push
